### ISSUE TITLE
officer_tables removes hyphens from text in tables

### ISSUE THREAD

**Issue by daviddiviny** [elipousson/officerExtras#1]
This is a very helpful package, thanks @elipousson 

Please let me know if you need a reprex, but I notice that when extracting tables using officer_tables, any hyphens in words are removed, e.g. "Inspector-General" becomes "InspectorGeneral". 

This occurred when extracting tables from the Australian Government Budget at this [link](https://budget.gov.au/content/bp4/download/bp4_05_agency_resourcing_tables.docx).

**Comment by elipousson** [comment]
Thanks for the report! A think this actually may be a bug in `officer::docx_summary()`. If you can open an issue over there, I'm happy to try to figure out the cause when I get a chance.
